# Generated by Django 3.2.4 on 2022-03-05 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predict', '0003_auto_20220305_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to='auth.user'),
            preserve_default=False,
        ),
    ]
