# Generated by Django 3.2.4 on 2022-03-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_historymodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
