# Generated by Django 3.2.4 on 2022-03-05 14:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predict', '0005_alter_historymodel_percentage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoryModel',
            new_name='History',
        ),
    ]
